image: alefesouza/php7-laravel-node-yarn

services:
  - mysql:5.7.20

variables:
  MYSQL_DATABASE: laravel_vue_boilerplate
  MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  DB_HOST: mysql
  DB_USERNAME: root
  DB_PASSWORD: ''

cache:
  paths:
  - node_modules/
  - vendor/

stages:
  - test

unit_test:
  stage: test
  script:
    - composer start
    - yarn start
