language: php

php:
  - 7.2

services:
  - mysql

cache:
  - node_modules
  - vendor

before_install:
  - nvm install 12
  - mysql -e 'CREATE DATABASE laravel_vue_boilerplate_test;'

before_script:
  - cp .env.testing.example .env
  - composer install -n --prefer-dist
  - composer run key:generate
  - composer run jwt:generate
  - php artisan vue-i18n:generate
  - php artisan migrate --seed
  - npm install
  - npm run ci

script:
  - composer test
  - npm test
