version: '3'

services:
  php:
    build: .
    container_name: laravel-vue-boilerplate
    ports:
      - 8000:80
    entrypoint: bash -c "echo -e \"`/sbin/ip route|awk '/default/ { print $$3 }'`\thost.docker.internal\" | tee -a /etc/hosts > /dev/null && /usr/local/bin/docker-php-entrypoint -k start"
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal default_enable=1 remote_port=9000 remote_enable=1 remote_handler=dbgp remote_connect_back=0 idekey=VSCODE remote_autostart=1
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/apache2/httpd-vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./:/var/www/html
    depends_on:
      - mysqldb
  myadmin:
    image: phpmyadmin/phpmyadmin:4.9
    container_name: lvb-phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_CONNECTION}
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    container_name: lvb-mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
