version: '3'

services:
  php:
    build: .
    container_name: laravel-vue-boilerplate
    ports:
      - 8000:80
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/apache2/httpd-vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./:/var/www/html
    depends_on:
      - mysqldb
  myadmin:
    image: phpmyadmin/phpmyadmin:4.9
    container_name: lvb-phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_CONNECTION}
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    container_name: lvb-mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
